"""Guards for resources/hero.svg -- the og:image / Twitter-card source.

Companion to tests/test_icon_masters.py, but hero.svg is deliberately NOT
held to that module's test_glyphs_are_paths_not_text rule: converting all
its text runs to vector paths is a real, larger job left as recorded debt
(2026-08-19 site-fix review, finding #6). What IS enforced here is the
narrower, actually-shipped fix: hero.svg must be generated by
resources/generate_hero_svg.py (not hand-tuned), its font stack must track
docs/index.html's --mono exactly, and it must stay well under
render_hero.py's MAX_BYTES budget for the rendered JPEG.
"""
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

import pytest

RESOURCES = Path(__file__).resolve().parent.parent / "resources"
HERO_SVG = RESOURCES / "hero.svg"
GENERATOR = RESOURCES / "generate_hero_svg.py"
sys.path.insert(0, str(RESOURCES))


def test_hero_svg_exists_and_is_well_formed():
    assert HERO_SVG.exists(), "resources/hero.svg is missing"
    ET.parse(HERO_SVG)  # raises ET.ParseError if not well-formed XML


def test_generator_is_committed():
    """Finding #6: the hand-tuned offsets that used to live in hero.svg had
    no source -- this is the fix, and it must actually be checked in."""
    assert GENERATOR.exists(), (
        "resources/generate_hero_svg.py must be committed so hero.svg's "
        "scene can be edited without recomputing offsets by hand"
    )


def test_hero_svg_font_stack_matches_docs_index_mono():
    """The og:image should read in the same typeface family as the live
    page's --mono token, not a stack that happens to omit one fallback.

    Compares font *names* rather than the raw string: docs/index.html's CSS
    quotes multi-word names with double quotes, hero.svg's SVG attribute
    (nested inside a double-quoted XML attribute) uses single quotes -- a
    byte-for-byte comparison would fail on that alone.
    """
    index_html = (RESOURCES.parent / "docs" / "index.html").read_text(encoding="utf-8")
    mono_match = re.search(r"--mono:\s*([^;]+);", index_html)
    assert mono_match, "--mono not found in docs/index.html"
    index_fonts = [f.strip().strip('"').strip("'") for f in mono_match.group(1).split(",")]

    svg_source = HERO_SVG.read_text(encoding="utf-8")
    ff_match = re.search(r'font-family="([^"]+)"', svg_source)
    assert ff_match, "no font-family attribute found in hero.svg"
    svg_fonts = [f.strip().strip('"').strip("'") for f in ff_match.group(1).split(",")]

    assert svg_fonts == index_fonts, (
        f"hero.svg font stack {svg_fonts} does not match docs/index.html's "
        f"--mono {index_fonts}"
    )
    assert "Liberation Mono" in svg_fonts


def test_hero_svg_byte_size_is_lean():
    """hero.svg itself (the tspan-flow source, not the rendered JPEG) should
    stay a small, text-based file -- a regression here (e.g. accidentally
    embedding a raster image) would be a sign something went very wrong."""
    size = HERO_SVG.stat().st_size
    assert size < 50_000, f"hero.svg is {size:,} bytes -- unexpectedly large for text-only SVG"


def test_rendered_jpeg_budget_matches_render_hero_config():
    """Keeps this test's understanding of the budget honest against the
    pipeline's own constant, the same pattern
    test_icon_outputs.py::test_ico_size_list_matches_the_pipeline uses for
    render_icons.ICO_SIZES."""
    render_hero = pytest.importorskip("render_hero", reason="asset tooling not installed")
    assert render_hero.MAX_BYTES == 350_000


def test_hero_svg_has_no_invented_cli_command():
    """Finding #1 companion: hero.svg is regenerated to match the live
    page's hero terminal, which no longer invents a `quickpdfocr` CLI
    command that does not exist (see tests/test_ascii_art.py and
    docs/index.html's hero terminal for the primary fix)."""
    # generate_hero_svg.py's word-spacing renders as NBSP (U+00A0), not a
    # regular space -- see its _escape()'s docstring comment for why -- so
    # normalize before substring-matching plain-English phrases.
    source = HERO_SVG.read_text(encoding="utf-8").replace("\u00A0", " ")
    assert "quickpdfocr scan" not in source
    assert "OCR in progress" in source, "hero.svg should depict the new status-readout scene"


def test_frame_rows_render_to_equal_widths():
    """The actual regression test for finding #6: every framed row (title
    bar, track, beam, fill, progress, status, closing frame) must render to
    the same pixel width when screenshotted, or the box will not visually
    close -- exactly the bug a hardcoded-offset, font-dependent hero.svg
    reintroduces on a different font (e.g. Windows/Consolas).

    Renders the real committed hero.svg through the same
    HTML-wrapper-plus-screenshot path render_hero.py uses, rather than
    re-running the generator (which always passes against itself) --
    exercising what's actually checked into the tree.
    """
    sync_playwright = pytest.importorskip(
        "playwright.sync_api", reason="asset tooling not installed"
    ).sync_playwright

    svg_markup = HERO_SVG.read_text(encoding="utf-8")
    wrapper = (
        '<!doctype html><html><head><meta charset="utf-8"></head>'
        '<body style="margin:0">%s</body></html>' % svg_markup
    )

    with sync_playwright() as p:
        browser = p.chromium.launch()
        try:
            page = browser.new_page(viewport={"width": 1920, "height": 1080})
            page.set_content(wrapper)
            widths = page.evaluate(
                """() => [...document.querySelectorAll('text')]
                    .map(t => ({len: t.textContent.length, w: t.getComputedTextLength()}))"""
            )
        finally:
            browser.close()

    # Frame rows are the ones whose raw text content is 46 characters (the
    # same column count docs/index.html's hero terminal enforces); the
    # shorter header/footer rows are excluded deliberately.
    framed = [w["w"] for w in widths if w["len"] == 46]
    assert len(framed) >= 5, f"expected several 46-column frame rows, found {len(framed)}"
    spread = max(framed) - min(framed)
    assert spread < 1.0, (
        f"framed rows in hero.svg render to inconsistent widths (spread "
        f"{spread:.2f}px) -- the frame will not visually close: {framed}"
    )
