"""Guards for resources/hero.svg -- the og:image / Twitter-card source.

Companion to tests/test_icon_masters.py, but hero.svg is deliberately NOT
held to that module's test_glyphs_are_paths_not_text rule: converting all
its text runs to vector paths is a real, larger job left as recorded debt
(2026-08-19 site-fix review, finding #6). What IS enforced here is the
narrower, actually-shipped fix: hero.svg must be generated by
resources/generate_hero_svg.py (not hand-tuned), its font stack must track
docs/index.html's --mono exactly, and it must stay well under
render_hero.py's MAX_BYTES budget for the rendered JPEG.
"""
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

import pytest

RESOURCES = Path(__file__).resolve().parent.parent / "resources"
HERO_SVG = RESOURCES / "hero.svg"
GENERATOR = RESOURCES / "generate_hero_svg.py"
sys.path.insert(0, str(RESOURCES))


def test_hero_svg_exists_and_is_well_formed():
    assert HERO_SVG.exists(), "resources/hero.svg is missing"
    ET.parse(HERO_SVG)  # raises ET.ParseError if not well-formed XML


def test_generator_is_committed():
    """Finding #6: the hand-tuned offsets that used to live in hero.svg had
    no source -- this is the fix, and it must actually be checked in."""
    assert GENERATOR.exists(), (
        "resources/generate_hero_svg.py must be committed so hero.svg's "
        "scene can be edited without recomputing offsets by hand"
    )


def test_hero_svg_font_stack_matches_docs_index_mono():
    """The og:image should read in the same typeface family as the live
    page's --mono token, not a stack that happens to omit one fallback.

    Compares font *names* rather than the raw string: docs/index.html's CSS
    quotes multi-word names with double quotes, hero.svg's SVG attribute
    (nested inside a double-quoted XML attribute) uses single quotes -- a
    byte-for-byte comparison would fail on that alone.
    """
    index_html = (RESOURCES.parent / "docs" / "index.html").read_text(encoding="utf-8")
    mono_match = re.search(r"--mono:\s*([^;]+);", index_html)
    assert mono_match, "--mono not found in docs/index.html"
    index_fonts = [f.strip().strip('"').strip("'") for f in mono_match.group(1).split(",")]

    svg_source = HERO_SVG.read_text(encoding="utf-8")
    ff_match = re.search(r'font-family="([^"]+)"', svg_source)
    assert ff_match, "no font-family attribute found in hero.svg"
    svg_fonts = [f.strip().strip('"').strip("'") for f in ff_match.group(1).split(",")]

    assert svg_fonts == index_fonts, (
        f"hero.svg font stack {svg_fonts} does not match docs/index.html's "
        f"--mono {index_fonts}"
    )
    assert "Liberation Mono" in svg_fonts


def test_generator_colours_match_docs_index_tokens():
    """Same drift risk as the font-stack check above, one property over:
    generate_hero_svg.py's INK/BEAM/FILL are hand-copied hex literals from
    docs/index.html's --frame/--accent/--bar-ink, with nothing before this
    cross-checking them. A future palette change in docs/index.html (this
    task already made one, to --slate-light) would leave the og:image on
    stale colours with every other test in this file still green.

    Imports generate_hero_svg as a plain module (no Playwright call happens
    at import time -- only inside _measure()/main()) rather than
    re-parsing its source, the same pattern
    tests/test_icon_outputs.py uses for render_icons.SIZE_SOURCES.
    """
    generate_hero_svg = pytest.importorskip(
        "generate_hero_svg", reason="asset tooling not installed"
    )
    index_html = (RESOURCES.parent / "docs" / "index.html").read_text(encoding="utf-8")
    tokens = dict(re.findall(r"(--[\w-]+):\s*(#[0-9A-Fa-f]{6})\s*;", index_html))
    assert generate_hero_svg.INK == tokens["--frame"]
    assert generate_hero_svg.BEAM == tokens["--accent"]
    assert generate_hero_svg.FILL == tokens["--bar-ink"]


def test_hero_svg_byte_size_is_lean():
    """hero.svg itself (the tspan-flow source, not the rendered JPEG) should
    stay a small, text-based file -- a regression here (e.g. accidentally
    embedding a raster image) would be a sign something went very wrong."""
    size = HERO_SVG.stat().st_size
    assert size < 50_000, f"hero.svg is {size:,} bytes -- unexpectedly large for text-only SVG"


def test_render_hero_derives_viewport_from_svg_dimensions(tmp_path):
    """Regression guard: render_hero.py's Playwright viewport must come from
    hero.svg's own <svg width/height>, not a hardcoded literal.

    _WRAPPER forces `svg { width: 100vw; height: 100vh }`, so the SVG is
    stretched to fill whatever viewport Playwright opens. A viewport that
    doesn't match the SVG's own aspect ratio silently distorts the render
    (non-uniform x/y scaling, not a crop) with nothing to catch it -- render_hero.py
    only validates XML well-formedness and a byte budget. This renders a
    synthetic, deliberately non-16:9 SVG (a plain square, easy to verify by
    pixel dimensions alone) through the real render_hero.main() and checks
    the output PNG comes out square, not stretched to whatever aspect ratio
    a hardcoded viewport would have forced.
    """
    Image = pytest.importorskip("PIL.Image", reason="Pillow is asset tooling")
    render_hero = pytest.importorskip("render_hero", reason="asset tooling not installed")
    pytest.importorskip(
        "playwright.sync_api", reason="asset tooling not installed"
    )

    tmp_resources = tmp_path / "resources"
    (tmp_resources / "_render").mkdir(parents=True)
    square_svg = tmp_resources / "hero.svg"
    square_svg.write_text(
        '<svg xmlns="http://www.w3.org/2000/svg" width="400" height="400">'
        '<rect width="400" height="400" fill="#0F172A"/>'
        '<circle cx="200" cy="200" r="150" fill="#818CF8"/>'
        "</svg>",
        encoding="utf-8",
    )

    original = (render_hero.RESOURCES, render_hero.SOURCE, render_hero.TARGET)
    render_hero.RESOURCES = tmp_resources
    render_hero.SOURCE = square_svg
    render_hero.TARGET = tmp_resources / "quick_pdf_hero_small.jpg"
    try:
        exit_code = render_hero.main()
    finally:
        render_hero.RESOURCES, render_hero.SOURCE, render_hero.TARGET = original

    assert exit_code == 0
    with Image.open(tmp_resources / "_render" / "hero.png") as im:
        assert im.size == (400, 400), (
            f"square 400x400 hero.svg rendered as {im.size} -- viewport did "
            "not track the SVG's own dimensions (a hardcoded 1920x1080 "
            "viewport would stretch this into a 16:9 rectangle instead)"
        )


def test_rendered_jpeg_budget_matches_render_hero_config():
    """Keeps this test's understanding of the budget honest against the
    pipeline's own constant, the same pattern
    test_icon_outputs.py::test_ico_size_list_matches_the_pipeline uses for
    render_icons.ICO_SIZES."""
    render_hero = pytest.importorskip("render_hero", reason="asset tooling not installed")
    assert render_hero.MAX_BYTES == 350_000


def test_hero_svg_has_no_invented_cli_command():
    """Finding #1 companion: hero.svg is regenerated to match the live
    page's hero terminal, which no longer invents a `quickpdfocr` CLI
    command that does not exist (see tests/test_ascii_art.py and
    docs/index.html's hero terminal for the primary fix)."""
    # generate_hero_svg.py's word-spacing renders as NBSP (U+00A0), not a
    # regular space -- see its _escape()'s docstring comment for why -- so
    # normalize before substring-matching plain-English phrases.
    source = HERO_SVG.read_text(encoding="utf-8").replace("\u00A0", " ")
    assert "quickpdfocr scan" not in source
    assert "OCR in progress" in source, "hero.svg should depict the new status-readout scene"


def test_hero_svg_rows_match_the_live_hero_terminal():
    """Stronger companion to the substring check above: hero.svg and
    docs/index.html's .hero-terminal <pre> are two hand-maintained copies of
    the same 11-line scene (a plain-string ROWS list in
    generate_hero_svg.py vs. the live page's actual markup) -- nothing
    before this enforced they describe the same content, so a future edit
    to either side (page count, word count, filename, wording) could leave
    every other test in this file green while the social preview silently
    diverges from what the page actually shows. Compares row by row, in
    order, both sides' tags stripped and NBSP normalized to a plain space.
    """
    from tests.test_ascii_art import _hero_text

    live_rows = [line for line in _hero_text().split("\n") if line.strip()]

    svg_source = HERO_SVG.read_text(encoding="utf-8")
    svg_rows = [
        re.sub(r"<[^>]+>", "", block).replace("\u00A0", " ")
        for block in re.findall(r"<text[^>]*>(.*?)</text>", svg_source, re.S)
    ]

    assert svg_rows == live_rows, (
        f"hero.svg's rows have drifted from docs/index.html's live hero "
        f"terminal:\nsvg:  {svg_rows}\nlive: {live_rows}"
    )

    # Direct source-of-truth assertion: the committed hero.svg must match the
    # generator's ROWS data structure, not just the live page. Flattens the
    # nonblank ROWS entries (each is a list of (text, color) tuples) into
    # plain text strings and compares them with the svg_rows already extracted
    # above, so a future edit to generate_hero_svg.ROWS that doesn't get
    # regenerated into hero.svg fails here instead of silently drifting.
    generate_hero_svg = pytest.importorskip(
        "generate_hero_svg", reason="asset tooling not installed"
    )
    source_rows = [
        "".join(text for text, _color in row)
        for row in generate_hero_svg.ROWS
        if row is not None
    ]
    # svg_rows already has NBSP normalized to plain space, so normalize
    # source_rows the same way for comparison
    source_rows_normalized = [row.replace("\u00A0", " ") for row in source_rows]
    assert svg_rows == source_rows_normalized, (
        f"hero.svg has drifted from generate_hero_svg.ROWS:\n"
        f"svg:    {svg_rows}\n"
        f"source: {source_rows_normalized}"
    )


def test_frame_rows_render_to_equal_widths():
    """The actual regression test for finding #6: every framed row (title
    bar, track, beam, fill, progress, status, closing frame) must render to
    the same pixel width when screenshotted, or the box will not visually
    close -- exactly the bug a hardcoded-offset, font-dependent hero.svg
    reintroduces on a different font (e.g. Windows/Consolas).

    Renders the real committed hero.svg through the same
    HTML-wrapper-plus-screenshot path render_hero.py uses, rather than
    re-running the generator (which always passes against itself) --
    exercising what's actually checked into the tree.
    """
    sync_playwright = pytest.importorskip(
        "playwright.sync_api", reason="asset tooling not installed"
    ).sync_playwright

    svg_markup = HERO_SVG.read_text(encoding="utf-8")
    wrapper = (
        '<!doctype html><html><head><meta charset="utf-8"></head>'
        '<body style="margin:0">%s</body></html>' % svg_markup
    )

    with sync_playwright() as p:
        browser = p.chromium.launch()
        try:
            page = browser.new_page(viewport={"width": 1920, "height": 1080})
            page.set_content(wrapper)
            widths = page.evaluate(
                """() => [...document.querySelectorAll('text')]
                    .map(t => ({len: t.textContent.length, w: t.getComputedTextLength()}))"""
            )
        finally:
            browser.close()

    # Frame rows are the ones whose raw text content is 46 characters (the
    # same column count docs/index.html's hero terminal enforces); the
    # shorter header/footer rows are excluded deliberately.
    framed = [w["w"] for w in widths if w["len"] == 46]
    assert len(framed) >= 5, f"expected several 46-column frame rows, found {len(framed)}"
    spread = max(framed) - min(framed)
    assert spread < 1.0, (
        f"framed rows in hero.svg render to inconsistent widths (spread "
        f"{spread:.2f}px) -- the frame will not visually close: {framed}"
    )
